engines:
  eslint:
    enabled: true
  csslint:
    enabled: false
  duplication:
    enabled: true
    config:
      languages:
      - javascript
ratings:
  paths:
  - "lib/**"
exclude_paths:
- "docs/**"